-- MySQL Script generated by MySQL Workbench
-- 12/08/19 17:01:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `pkIdCategoria` INT(11) NOT NULL COMMENT 'Este atributo es el identificador y llave primaria de la tabla, dato unico e irrepetible y no admite datos nulos.',
  `nombreCategoria` VARCHAR(45) NOT NULL COMMENT 'Este atributo almacena los datos que representan los nombres de las categorias de cada producto y no admite datos nulos.',
  PRIMARY KEY (`pkIdCategoria`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'La presente tabla almacena los datos de nombre de la categoria del producto y se identifica con un ID unico.';


-- -----------------------------------------------------
-- Table `mydb`.`Documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Documento` (
  `idTipoDocumento` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Este atributo es la llave primaria, por lo cual es irrepetible y obligatorio. Este almacena el dato de identificador de la tabla y es de tipo entero.',
  `nombreDocumento` VARCHAR(45) NOT NULL COMMENT 'Este atributo almacena el dato que se designa a la descripcion del documento. Cuenta con obligatoriedad y es de tipo varchar.',
  PRIMARY KEY (`idTipoDocumento`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COMMENT = 'En la presente tabla se tiene un Id como identificador, este es la llave primaria. tambien se encuentra el nombre del documento para la descripcion del mismo.';


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `pkIdPersona` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Este atributo, representa y almacena el id de la persona. Este es un dato unico e irrepetible dentro de la tabla y es de caracter obligatorio.',
  `fkIdDocumento` INT(20) NOT NULL COMMENT 'Este atributo, representa y almacena el id del documento, es una llave foranea hereda de la tabla denominada Documento, es un dato con obligatoriedad y de tipo entero.',
  `nombre` VARCHAR(70) NOT NULL COMMENT 'En este atributo se almacena el dato correspondiente al nombre de la persona. Este es de tipo Varchar para permitir datos alfa-numericos y cuenta con obligatoriedad.',
  `apellido` VARCHAR(120) NOT NULL COMMENT 'En este atributo se almacena el dato referente al apellido de la persona. Esta es de tipo Varchar para permitir datos alfa-numericos y es de caracter obligatorio',
  `correoElectronico` VARCHAR(45) NULL COMMENT 'En este atributo se almacena el dato correspondiente al correo Electronico. Este es de tipo Varchar para permitir datos alfa-numericos sin embargo no es obligatorio.',
  PRIMARY KEY (`pkIdPersona`)  COMMENT '',
  INDEX `idDocumento_idx` (`fkIdDocumento` ASC)  COMMENT '',
  CONSTRAINT `idDocumento`
    FOREIGN KEY (`fkIdDocumento`)
    REFERENCES `mydb`.`Documento` (`idTipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8
COMMENT = 'En la presente tabla se almacenan los datos correspondientes a la persona. Tiene como atributos, idPersona, IdDocumento, nombre, apellido y correoElectronico.';


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `Personas_pkIdPersona` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Este atributo identificado como llave primaria que proviene de la tabla denominada Persona, este es de tipo entero y de caracter obligatorio.',
  `genero` VARCHAR(45) NOT NULL COMMENT 'En este atributo se almacena el dato que especifica si el cliente es de genero masculino, femenino u otro. No se permite dato nulos y es varchar.',
  `edad` INT(11) NOT NULL COMMENT 'Dentro de este atributo se guarda el dato de la edad de un cliente, este es not null y de tipo entero. Su funcion es permitir a futuro estadisticas de compra por el cliente. ',
  PRIMARY KEY (`Personas_pkIdPersona`)  COMMENT '',
  INDEX `fk_Cliente_Personas1_idx` (`Personas_pkIdPersona` ASC)  COMMENT '',
  CONSTRAINT `fk_Cliente_Personas1`
    FOREIGN KEY (`Personas_pkIdPersona`)
    REFERENCES `mydb`.`Persona` (`pkIdPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COMMENT = 'La presente tabla almacena los datos que tendra especificamente el cliente, los cuales son el genero y la edad, que estara identificado por un id, unico e irrepetible. ';


-- -----------------------------------------------------
-- Table `mydb`.`Contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contacto` (
  `Persona_pkIdPersona` INT(11) NOT NULL COMMENT 'Este atributo, indica el id de la persona. Se encuentra como llave foranea para aplicar varios datos telefonicos si se considera pertinente; proviene de la tabla denominada Persona. Este es de tipo notnull sy entero.',
  `telefono` INT(11) NOT NULL COMMENT 'Dentro de este atributo se almacena el numero telefonico de la persona. Es un dato obligatorio en primera instancia y es guardado solamente en entero.',
  INDEX `fk_Contacto_Persona1_idx` (`Persona_pkIdPersona` ASC)  COMMENT '',
  CONSTRAINT `fk_Contacto_Persona1`
    FOREIGN KEY (`Persona_pkIdPersona`)
    REFERENCES `mydb`.`Persona` (`pkIdPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8
COMMENT = 'En la presente tabla se almacena el numero de contacto para la persona existente en el sistema, por ello se usa la llave foranea persona (la identidad) para agregar mas datos si se considera pertinente.';


-- -----------------------------------------------------
-- Table `mydb`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factura` (
  `pkIdFactura` INT(11) NOT NULL COMMENT 'Este atributo, indica el id de la factura. Se encuentra como llave primaria para la identidad de la factura. Este es de tipo entero y obligatorio.',
  `Cliente_Personas_pkIdPersona` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Este atributo, indica el id del cliente. Se encuentra como llave foranea, proveniente de la tabla denominada Cliente, y  para generar varios registros del mismo. Este es de tipo entero y obligatorio.',
  `fechaFactura` DATE NOT NULL COMMENT 'En el campo de este atributo se almacena el dato de la fecha facturada de compra realizada por el cliente. Es de tipo Date y con obligatoriedad.',
  PRIMARY KEY (`pkIdFactura`)  COMMENT '',
  INDEX `fk_Factura_Cliente1_idx` (`Cliente_Personas_pkIdPersona` ASC)  COMMENT '',
  CONSTRAINT `fk_Factura_Cliente1`
    FOREIGN KEY (`Cliente_Personas_pkIdPersona`)
    REFERENCES `mydb`.`Cliente` (`Personas_pkIdPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COMMENT = 'En la presente tabla se almacena los datos correspondientes a la factura de venta al cliente. Ésta, tiene un id único e irrepetible. sus atributos son la anteriormencionada, idCliente y fecha. ';


-- -----------------------------------------------------
-- Table `mydb`.`Permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Permiso` (
  `pkIdPermisos` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Este atributo es la llave primaria, es de tipo entero y no permite omision (es obligatorio). En él se almacena el dato que identifica el permiso.',
  `nombrePermiso` VARCHAR(45) NOT NULL COMMENT 'Este atributo es de tipo varchar y cuenta con obligatoriedad; en él se almacena el dato para especificar el nombre del permiso.',
  PRIMARY KEY (`pkIdPermisos`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'En la presente tabla se alojan los datos correspondientes de los permisos que tendran asignados los usuarios. Este tiene un id de caracter llave primaria y el nombre del permiso, para especificar la misma.';


-- -----------------------------------------------------
-- Table `mydb`.`RolUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RolUsuario` (
  `pkIdRol` INT(11) NOT NULL COMMENT 'Este atributo, representa y almacena el id del Rol disponible para el usuario; es una llave primaria, siendo de tipo entero y de caracter obligatorio.',
  `nombreRol` VARCHAR(45) NOT NULL COMMENT 'En este atributo se almacena el dato correspondiente al nombre del rol, para describirlo. Este es de tipo Varchar para permitir datos alfa-numericos y es notnull.',
  PRIMARY KEY (`pkIdRol`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'En la presente tabla, se encuentra los atributos del rol de usuario, tiene una llave primaria, idRol y nombreRol para la descripcion del rol.';


-- -----------------------------------------------------
-- Table `mydb`.`PermisoRol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PermisoRol` (
  `Rol_pkIdRol` INT(11) NOT NULL COMMENT 'Este atributo es una llave foranea heredada de la tabla denominada Rol; es de tipo entero y no permite omision (es obligatorio). En él se almacena el dato que identifica el permisoy permite ser repetida.',
  `Permiso_pkIdPermiso` INT(11) NOT NULL COMMENT 'Este atributo es una llave foranea, puesto que proviene de la tabla denominada Permiso;se caracteriza por ser de tipo entero y no permite omision (es obligatorio). En él se almacena el dato que identifican el roly permite ser repetido',
  INDEX `fk_PermisosRol_Rol1_idx` (`Rol_pkIdRol` ASC)  COMMENT '',
  INDEX `fk_PermisosRol_Permiso1_idx` (`Permiso_pkIdPermiso` ASC)  COMMENT '',
  CONSTRAINT `fk_permisos`
    FOREIGN KEY (`Permiso_pkIdPermiso`)
    REFERENCES `mydb`.`Permiso` (`pkIdPermisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles`
    FOREIGN KEY (`Rol_pkIdRol`)
    REFERENCES `mydb`.`RolUsuario` (`pkIdRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'En la presente tabla se encuentran los atributos idRol y  idPermiso; ambos atributos son llaves foraneas y son de tipo entero.';


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `pkIdProducto` INT(11) NOT NULL COMMENT 'Este atributo, representa y almacena el id del producto. Este es un dato unico e irrepetible dentro de la tabla es entero y de caracter obligatorio.',
  `Categoria_pkIdCategoria` INT(11) NOT NULL COMMENT 'Este atributo, representa y almacena el id de la categoria que pertenence el producto. Es una llave foranea que proviene de la tabla denominada Categoria; este es un dato unico e irrepetible y de caracter obligatorio.',
  `nombreProducto` VARCHAR(45) NOT NULL COMMENT 'En este atributo se almacena el dato referente al nombre del producto que ingresa al inventario. Esta es de tipo Varchar para permitir datos alfa-numericos y de caracter obligatorio.',
  `caducidad` DATE NULL COMMENT 'Este atributo, almacena el dato designado a la vida util del producto. Este es un dato sin obligatoriedad y se guarda como DATE.',
  PRIMARY KEY (`pkIdProducto`)  COMMENT '',
  INDEX `fk_Producto_Categoria1_idx` (`Categoria_pkIdCategoria` ASC)  COMMENT '',
  CONSTRAINT `fk_Producto_Categoria1`
    FOREIGN KEY (`Categoria_pkIdCategoria`)
    REFERENCES `mydb`.`Categoria` (`pkIdCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`ProductoVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProductoVenta` (
  `Producto_pkIdProducto` INT(11) NOT NULL COMMENT 'Este atributo, representa y almacena el id del producto para la venta. Este es un dato unico e irrepetible (dado que es llave primaria) dentro de la tabla es entero y de caracter obligatorio.',
  `cantidad` INT(12) NOT NULL COMMENT 'En este atributo se almacena el dato referente a la cantidad del producto perteneciente en el inventario de la empresa. Este es de tipo entero y notnull.',
  `PrecioVenta` INT(10) NOT NULL COMMENT 'En este atributo se almacena el dato correspondiente al precio unitario que se pone en venta por la empresa. Este es de tipo entero para permitir solamente datos numericos y es de caracter obligatorio.',
  `iva` DECIMAL(8) NOT NULL COMMENT 'Dentro de este atributo se almacena el dato correspondiente al iva del producto. Este es de tipo decimal y de igual manera es obligatorio.',
  INDEX `fk_ProductoConsumible_ProductoObjeto1_idx` (`Producto_pkIdProducto` ASC)  COMMENT '',
  PRIMARY KEY (`Producto_pkIdProducto`)  COMMENT '',
  CONSTRAINT `fk_ProductoConsumible_ProductoObjeto1`
    FOREIGN KEY (`Producto_pkIdProducto`)
    REFERENCES `mydb`.`Producto` (`pkIdProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'En la presente tabla, se alojan los atributos del producto en venta al cliente; estos son, id del producto, cantidad, precioVenta e iva.';


-- -----------------------------------------------------
-- Table `mydb`.`ProductoFactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProductoFactura` (
  `Factura_pkIdFactura` INT(11) NOT NULL COMMENT 'Dentro de este atributo se almacena el id de la factura. Este es una foranea que proviene de la tabla denominada Factura, permite multiples datos dentro esta sin embargo es de caracter obligatorio y entero.\n',
  `Producto_pkIdProducto` INT(11) NOT NULL COMMENT 'Dentro de este atributo se almacena el id del producto. Este es una foranea que proviene de la tabla denominada Producto, es el indicador del producto solicitado por el cliente; permite multiples datos dentro esta sin embargo es de caracter obligatorio y entero.\n',
  `cantidadVenta` INT(8) NOT NULL COMMENT 'En este atributo se almacena el dato correspondiente a la cantidad del producto dado en venta al cliente. Este es de tipo entero puesto que solamente permite datos numericos y de igual forma es de caracter obligatorio.',
  `subtotal` INT(8) NOT NULL COMMENT 'En este atributo se almacena el dato referente al subtotal (producto sin iva+ cantidad) de la venta realizada al cliente. Este es de tipo entero para permitir solamente datos numericos y se caracteriza por ser obligatorio.',
  `iva` DECIMAL(8) NOT NULL COMMENT 'En este atributo se almacena el dato referente al iva de la compra general de productos hecho por el cliente. Este es de tipo decimal para permitir el manejo de datos decimales y de caracter notnull.',
  `totalVenta` INT(10) NOT NULL COMMENT 'En este atributo se almacena el dato correspondiente al valor total de la venta (subtotal+ iva). Este es de tipo entero para permitir solamente datos numericos y de tipo notnull.',
  INDEX `fk_Producto_has_Factura_Factura1_idx` (`Factura_pkIdFactura` ASC)  COMMENT '',
  CONSTRAINT `fk_Producto_has_Factura_Factura1`
    FOREIGN KEY (`Factura_pkIdFactura`)
    REFERENCES `mydb`.`Factura` (`pkIdFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productofactura_ProductoVenta1`
    FOREIGN KEY (`Producto_pkIdProducto`)
    REFERENCES `mydb`.`ProductoVenta` (`Producto_pkIdProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'En la presente tabla se almacena los datos correspondientes al producto comprado por el cliente. Ésta, tiene un id de factura y un id del producto, estas son foraneas. Adicional a ello, tiene como atributos cantidadVenta, subtotal, iva y totalVenta.';


-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor` (
  `Persona_pkIdPersona` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Este atributo, representa y almacena el id del proveedor; en si es una llave primaria que proviene de la tabla denominada Persona. Este es un dato unico e irrepetible dentro de la tabla es entero y de caracter obligatorio.',
  `tipoProducto` VARCHAR(45) NOT NULL COMMENT 'Este atributo almacena el dato designado al tipo de producto que suministra el proveedor. Este es de tipo varchar y cuenta con obligatoriedad.',
  `Direccion` VARCHAR(45) NOT NULL COMMENT 'Este atributo almacena el dato referente a la direccion del proveedor. Este es de tipo varchar y cuenta con obligatoriedad.',
  PRIMARY KEY (`Persona_pkIdPersona`)  COMMENT '',
  CONSTRAINT `fk_Proveedor_Persona1`
    FOREIGN KEY (`Persona_pkIdPersona`)
    REFERENCES `mydb`.`Persona` (`pkIdPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8
COMMENT = 'En la presente tabla, se alojan los atributos pertenecientes al proveedor; estos son, id Persona, tipoProducto y direccion.';


-- -----------------------------------------------------
-- Table `mydb`.`ProveedorProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProveedorProducto` (
  `Proveedor_Persona_pkIdPersona` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Este atributo, representa y almacena el id del proveedor; en si es una llave foranea que proviene de la tabla denominada Persona. Este es entero y de caracter obligatorio.',
  `Producto_pkIdProducto` INT(11) NOT NULL COMMENT 'Este atributo almacena el dato designado al producto que suministra el proveedor, es una llave foranea proveniente de la tabla producto. Este es de tipo varchar y cuenta con obligatoriedad.',
  INDEX `fk_Proveedor_has_Producto_Producto1_idx` (`Producto_pkIdProducto` ASC)  COMMENT '',
  INDEX `fk_Proveedor_has_Producto_Proveedor1_idx` (`Proveedor_Persona_pkIdPersona` ASC)  COMMENT '',
  CONSTRAINT `fk_Proveedor_has_Producto_Producto1`
    FOREIGN KEY (`Producto_pkIdProducto`)
    REFERENCES `mydb`.`Producto` (`pkIdProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proveedor_has_Producto_Proveedor1`
    FOREIGN KEY (`Proveedor_Persona_pkIdPersona`)
    REFERENCES `mydb`.`Proveedor` (`Persona_pkIdPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8
COMMENT = 'En la presente tabla, se alojan los atributos necesarios para la solicitud de productos mediante una orden de compra; estos son, id orden de compra, productoRequerido, valorUnitario, ivaProducto, cantidadProducto, subtotal, ivaTotal y valorTotal.';


-- -----------------------------------------------------
-- Table `mydb`.`Trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Trabajador` (
  `Persona_pkIdPersona` INT(11) NOT NULL COMMENT 'Este atributo, representa y almacena el id del trabajador; en si es una llave primaria que proviene de la tabla denominada Persona. Este es un dato unico e irrepetible dentro de la tabla, es entero y de caracter obligatorio.',
  `fechaContratacion` DATE NOT NULL COMMENT 'Este atributo, almacena el dato referente a la fecha de contratacion. Este es un dato notnull y  se guarda como DATE.',
  `direccion` VARCHAR(45) NOT NULL COMMENT 'Este atributo representa y almacena el dato correspondiente a la direccion del trabajador. Este es de tipo Varchar para el ingreso de datos alfa-numericos y de caracter obligatorio.',
  `cargo` VARCHAR(45) NOT NULL COMMENT 'En este atributo se almacena el dato referente al cargo designado en empresa para el trabajado. Este es de tipo Varchar para permitir datos alfa-numericos y cuenta con obligatoriedad.',
  `eps` VARCHAR(45) NOT NULL COMMENT 'En este atributo se almacena el dato designado a la EPS del trabajador. Este es de tipo Varchar para permitir datos alfa-numericos y de caracter obligatorio.',
  PRIMARY KEY (`Persona_pkIdPersona`)  COMMENT '',
  CONSTRAINT `fk_trabajador_Personas1`
    FOREIGN KEY (`Persona_pkIdPersona`)
    REFERENCES `mydb`.`Persona` (`pkIdPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'La presente tabla, contiene un id Persona para el identificador del trabajador, adicional a ello, estan los atributos, fechaContratacion, Direccion, cargo y eps.';


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `trabajador_Personas_pkIdPersona` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Este atributo, representa y almacena el id del trabajador que posee usuario;es una llave primaria que proviene de la tabla denominada Trabajador. Este es un dato unico e irrepetible dentro de la tabla es entero y de caracter obligatorio.',
  `Rol_pkIdRol` INT(11) NOT NULL COMMENT 'Este atributo, almacena el id del rol que tiene el usuario;es una llave foranea que proviene de la tabla denominada RolUsuario. Este es un dato unico, entero, repetible y de caracter obligatorio.',
  `nombreUsuario` VARCHAR(45) NOT NULL COMMENT 'En este atributo se almacena el dato referente al nombre designado al usuario, como descripcion. Este es de tipo Varchar para permitir datos alfa-numericos y de tipo obligatorio.',
  `contraseña` VARCHAR(45) NOT NULL COMMENT 'En este atributo se almacena el dato correspondiente a la contraseña de usuario. Este es de tipo Varchar para permitir datos alfa-numericos y es de tipo notnull.',
  PRIMARY KEY (`trabajador_Personas_pkIdPersona`)  COMMENT '',
  INDEX `fk_Usuario_Rol1_idx` (`Rol_pkIdRol` ASC)  COMMENT '',
  CONSTRAINT `fk_Usuario_Rol1`
    FOREIGN KEY (`Rol_pkIdRol`)
    REFERENCES `mydb`.`RolUsuario` (`pkIdRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_trabajador1`
    FOREIGN KEY (`trabajador_Personas_pkIdPersona`)
    REFERENCES `mydb`.`Trabajador` (`Persona_pkIdPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8
COMMENT = 'La presente tabla, contiene un id Persona para el identificador del trabajador que tiene usuario. Ademas, estan los atributos, id rol, nombre usuario y contraseña.';


-- -----------------------------------------------------
-- Table `mydb`.`OrdenCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrdenCompra` (
  `idOrdenCompra` INT NOT NULL COMMENT 'Este atributo, representa el identificador del pedido. Este es un dato unico e irrepetible dentro de la tabla y es de caracter obligatorio.',
  `fechaOrdenCompra` DATE NOT NULL COMMENT 'Este atributo almacena el dato referente a la fecha que se solicita el pedido. Este se caracteriza por ser de tipo DATE para el manejo de tal formato y es notnull.',
  `proveedor_Persona_pkIdPersona` INT(11) NOT NULL COMMENT 'Este atributo, es una llave foranea proveniente de la tabla denominada Proveedor, se almacena de este modo para repeticiones posteriores. Representa la identificación única, obligatoria y es de tipo entero . En este se almacena el id del proveedor.',
  PRIMARY KEY (`idOrdenCompra`)  COMMENT '',
  INDEX `fk_OrdenCompra_proveedor1_idx` (`proveedor_Persona_pkIdPersona` ASC)  COMMENT '',
  CONSTRAINT `fk_OrdenCompra_proveedor1`
    FOREIGN KEY (`proveedor_Persona_pkIdPersona`)
    REFERENCES `mydb`.`Proveedor` (`Persona_pkIdPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'La presente tabla se encuentra identificada bajo un ID de llave primaria para el control de pedidos al proveedor. Esta conformado por fecha del pedido y del id del proveedor.';


-- -----------------------------------------------------
-- Table `mydb`.`ProductoSolicitadoP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProductoSolicitadoP` (
  `OrdenCompra_idOrdenCompra` INT NOT NULL COMMENT 'Este atributo, representa el identificador de la solicitud de pedido, es una llave foranea hereda de la tabla denominada OrdenCompra es un dato unico e irrepetible y de tipo obligatorio.',
  `productoRequerido` VARCHAR(30) NOT NULL COMMENT 'En este atributo se almacena el dato referente al nombre del producto solicitado. Este es de tipo Varchar para permitir datos alfa-numericos y cuenta con obligatoriedad',
  `valorUnitario` INT(8) NOT NULL COMMENT 'En este atributo se almacena el dato referente al precio unitario de costo del producto que se este solicitando. Este es de tipo entero para permitir solamente datos numericos y es de caracter obligatorio.',
  `ivaProducto` DECIMAL(7) NOT NULL COMMENT 'Dentro de este atributo se almacena el dato correspondiente al iva del producto en peticion al proveedor. Este es de tipo decimal y de igual manera es obligatorio.',
  `cantidadProducto` INT(7) NOT NULL COMMENT 'En este atributo se almacena el dato referente a la cantidad del producto requerido. Esta es de tipo entero y notnull',
  `subTotal` INT(10) NOT NULL COMMENT 'En este atributo se almacena el dato correspondiente al subtotal de la orden de compra de los productos pedidos. Este es de tipo entero para permitir solamente datos numericos y de caracter notnull.',
  `ivaTotal` DECIMAL(7) NOT NULL COMMENT 'En este atributo se almacena el dato referente al iva general de la orden de compra. Este es de tipo decimal para permitir el manejo de datos decimales.',
  `valorTotal` VARCHAR(10) NOT NULL COMMENT 'En este atributo se almacena el dato correspondiente al total de la peticion de productos. Este es de tipo entero y obligatorio.',
  CONSTRAINT `fk_ProductosSolicitados_OrdenCompra1`
    FOREIGN KEY (`OrdenCompra_idOrdenCompra`)
    REFERENCES `mydb`.`OrdenCompra` (`idOrdenCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'En la presente tabla, se alojan los atributos necesarios para la solicitud de productos mediante una orden de compra; estos son, id orden de compra, productoRequerido, valorUnitario, ivaProducto, cantidadProducto, subtotal, ivaTotal y valorTotal.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
